export const CREATE_DECK_SUCCESS = 'CREATE_DECK_SUCCESS';
export const SHUFFLE_DECK_SUCCESS = 'SHUFFLE_DECK_SUCCESS';
export const SORT_BY_CARD_VALUE_SUCCESS = 'SORT_BY_CARD_VALUE_SUCCESS';
export const SORT_BY_SUIT_VALUE_SUCCESS = 'SORT_BY_SUIT_VALUE_SUCCESS';